apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # echo -n mongouser | base64  bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA== # echo -n mongopassword | base64
